if ! test "${DOTFILES_DEBUG+define}"; then echo "Entering .dotfiles/bash/DOTFILES_OS_PLACEHOLDER/user/bashrc"; fi

if ! test "${DOTFILES_DEBUG+define}"; then echo "Leaving .dotfiles/bash/DOTFILES_OS_PLACEHOLDER/user/bashrc"; fi