if ! test "${DOTFILES_DEBUG+define}"; then echo "Entering .dotfiles/bash/oscer/user/bash_profile"; fi

module load git/2.36.0-GCCcore-11.3.0-nodocs.lua
module load Miniconda3/4.4.10

if ! test "${DOTFILES_DEBUG+define}"; then echo "Leaving .dotfiles/bash/oscer/user/bash_profile"; fi