if ! test "${DOTFILES_DEBUG+define}"; then echo "Entering .dotfiles/bash/oscer/user/bash_profile"; fi

module load git/2.36.0-GCCcore-11.3.0-nodocs.lua
module load Anaconda3/5.3.0

if ! test "${DOTFILES_DEBUG+define}"; then echo "Leaving .dotfiles/bash/oscer/user/bash_profile"; fi