if ! test "${DOTFILES_DEBUG+define}"; then echo "Entering .dotfiles/bash/cyg/shared/bash_profile"; fi

if ! test "${DOTFILES_DEBUG+define}"; then echo "Leaving .dotfiles/bash/cyg/shared/bash_profile"; fi