if ! test "${DOTFILES_DEBUG+define}"; then echo "Entering .dotfiles/bash/cyg/shared/bash_profile"; fi

. "${HOME}/.dotfiles/bash/cyg/shared/git-completion.bash"
. "${HOME}/.dotfiles/bash/cyg/shared/git-prompt.sh"
export GIT_PS1_SHOWDIRTYSTATE=1
export PS1='\w$(__git_ps1 " (%s)")\$ '

if ! test "${DOTFILES_DEBUG+define}"; then echo "Leaving .dotfiles/bash/cyg/shared/bash_profile"; fi