[[ "${DOTFILES_DEBUG}" = "true" ]] && echo "Entering .dotfiles/bash/cygwin_laptop/user/bash_profile"

[[ "${DOTFILES_DEBUG}" = "true" ]] && echo "Leaving .dotfiles/bash/cygwin_laptop/user/bash_profile"
