[[ "${DOTFILES_DEBUG}" = "true" ]] && echo "Entering .dotfiles/bash/DOTFILES_OS_PLACEHOLDER/shared/bashrc"

[[ "${DOTFILES_DEBUG}" = "true" ]] && echo "Leaving .dotfiles/bash/DOTFILES_OS_PLACEHOLDER/shared/bashrc"
