[[ "${DOTFILES_DEBUG}" = "true" ]] && echo "Entering ${DOTFILES_HOME}/.dotfiles/bash/DOTFILES_OS_PLACEHOLDER/shared/bash_profile"

[[ "${DOTFILES_DEBUG}" = "true" ]] && echo "Leaving ${DOTFILES_HOME}/.dotfiles/bash/DOTFILES_OS_PLACEHOLDER/shared/bash_profile"
